import {Todo} from "../models/todo.model.js";

export const getTodos = async (req, res) => {
  try {
    const todos = await Todo.find();
    res.status(200).json(todos);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

export const getTodoById = async (req,res) => {
  try {
    const todo = await Todo.findById(req.params.id);
    if (!todo) return res.status(404).json({ message: "Todo not found !" });
    res.status(200).json(todo);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};


export const createTodo=async (req,res)=>{
    const todo=new Todo(req.body);
    try {
        const savedTodo=await todo.save();
        res.status(201).json(savedTodo);
    } catch (error) {
        res.status(400).json({message:error.message});
    }
};

export const updateTodo=async (req,res)=>{
    try {
        const updatedTodo=await Todo.findByIdAndUpdate(req.params.id,req.body,{new:true});
        if(!updatedTodo) return res.status(404).json({message:"Todo not found !"});
        res.status(200).json(updatedTodo);
    } catch (error) {
        res.status(400).json({message:error.message});
    }

};


export const deleteTodo=async (req,res)=>{
    try {
        const deletedTodo=await Todo.findByIdAndDelete(req.params.id);
        if(!deletedTodo) return res.status(404).json({message:"Todo not found !"});
        res.status(200).json({message:"Todo deleted successfully !"});
    } catch (error) {
        res.status(500).json({message:error.message});
    }

};